on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/as1r@build
      with:
        branch: upstream
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}
